spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-pi
            predicates:
              - Path=/api/auth/**, /api/users/**
            filters:
              - StripPrefix=0

          - id: community-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/community/**
            filters:
              - StripPrefix=0