server:
  port: 8091

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-pi
            predicates:
              - Path=/api/auth/**, /api/users/**
            filters:
              - StripPrefix=0

          - id: event-service
            uri: lb://event-pi
            predicates:
              - Path=/api/events/**, /api/weather, /api/weather/**, /api/verify/**, /api/tickets/**, /api/registrations/**, /api/speakers/**, /api/programs/**, /api/feedback/**, /api/badges/**, /api/certificates/**, /api/predictions/**
            filters:
              - StripPrefix=0

          - id: community-service
            uri: lb://community-service
            predicates:
              - Path=/api/community/**
            filters:
              - StripPrefix=0

          - id: partenariat-service
            uri: lb://partenariat-pi
            predicates:
              - Path=/api/organisations/**, /api/conventions/**, /api/objectifs/**, /api/meeting-invitations/**, /api/zoom/**
            filters:
              - StripPrefix=0

          - id: legal-service
            uri: lb://legal-pi
            predicates:
              - Path=/api/legal-procedures, /api/legal-procedures/**, /api/procedure-types/**, /api/procedure-types, /api/files/**
            filters:
              - StripPrefix=0

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
