spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-pi
            predicates:
              - Path=/api/auth/**, /api/users/**
            filters:
              - StripPrefix=0
