spring.application.name=user-pi
server.port=8081

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/user_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=968828376271-3oc9k13pvr1hjq30tjqqhmi39mdvuviq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8090/login/oauth2/code/google

# ADD THIS ? tells Eureka the exact instance id
eureka.instance.instance-id=${spring.application.name}:${server.port}

# EMAIL CONFIGURATION
# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codedon10@gmail.com
spring.mail.password=abwr jajg odpf ihqy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.debug=true