apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-pi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-pi
  template:
    metadata:
      labels:
        app: user-pi
    spec:
      containers:
        - name: user-pi
          image: zainebt/user-pi:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-server:8761/eureka/
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
