import { ChangeDetectionStrategy, Component, signal, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import {
  lucideMap, lucidePlus, lucideCheck, lucideCircle, lucideClock,
  lucideCalendar, lucideEdit, lucideTrash, lucideArrowRight,
  lucideTarget, lucideZap, lucideFlag, lucideX, lucideRefreshCw,
} from '@ng-icons/lucide';
import { ProjectService } from '../../core/services/project.service';
import { Project } from '../../models/project';

interface RoadmapStep {
  phase: string;
  title: string;
  description: string;
  dueDate: string;
  status: 'completed' | 'in-progress' | 'pending';
  tasks: { label: string; done: boolean }[];
}

@Component({
  selector: 'app-roadmaps',
  standalone: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideIcons({
    lucideMap, lucidePlus, lucideCheck, lucideCircle, lucideClock,
    lucideCalendar, lucideEdit, lucideTrash, lucideArrowRight,
    lucideTarget, lucideZap, lucideFlag, lucideX, lucideRefreshCw,
  })],
  template: `
    <div class="page-shell">

      <!-- Header -->
      <div class="page-header">
        <div>
          <h2 class="text-lg font-bold" style="color:var(--text-primary); letter-spacing:-0.02em;">Roadmaps</h2>
          <p class="text-xs mt-0.5" style="color:var(--text-secondary);">Track your startup journey milestones</p>
        </div>
        <div class="page-header-actions">
          <button (click)="showProjectSelector.set(true)" class="text-xs font-semibold rounded-lg border cursor-pointer"
            style="background:var(--surface); color:var(--text-body); border-color:var(--border); padding:7px 14px;">
            <ng-icon name="lucideTarget" [size]="'13'" style="display:inline; margin-right:4px;" />
            {{ selectedProject() ? selectedProject()!.title : 'Select Project' }}
          </button>
          <button (click)="regenerateRoadmap()" [disabled]="!selectedProject() || generating()" class="text-xs font-semibold rounded-lg border cursor-pointer"
            style="background:var(--surface); color:var(--text-body); border-color:var(--border); padding:7px 14px;">
            <ng-icon name="lucideRefreshCw" [size]="'13'" style="display:inline; margin-right:4px;" />
            Regenerate
          </button>
          <button (click)="showAddStep.set(true)" class="flex items-center gap-1.5 text-xs font-semibold rounded-lg border-none cursor-pointer"
            style="background:linear-gradient(135deg,#1C4FC3,#1D1384); color:#fff; padding:8px 16px;">
            <ng-icon name="lucidePlus" [size]="'14'" />
            Add Step
          </button>
        </div>
      </div>

      <!-- Loading State -->
      @if (loading() || generating()) {
        <div class="flex items-center justify-center py-12">
          <div class="text-center">
            <div class="w-12 h-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
            <p class="text-sm text-gray-500">{{ loading() ? 'Loading projects...' : 'Generating roadmap...' }}</p>
          </div>
        </div>
      }

      <!-- Error State -->
      @if (error()) {
        <div class="rounded-xl border p-4 mb-4" style="background:#FEF2F2; border-color:#FCA5A5;">
          <p class="text-sm text-red-600">{{ error() }}</p>
        </div>
      }

      <!-- No Project Selected -->
      @if (!selectedProject() && !loading()) {
        <div class="flex flex-col items-center justify-center py-16">
          <div class="w-20 h-20 bg-blue-50 rounded-2xl flex items-center justify-center mb-4">
            <ng-icon name="lucideMap" [size]="'32'" style="color:#1D1384;" />
          </div>
          <h3 class="text-lg font-bold mb-2" style="color:var(--text-primary);">Select a Project</h3>
          <p class="text-sm text-gray-500 mb-6">Choose a project to generate its roadmap</p>
          <button (click)="showProjectSelector.set(true)" class="px-6 py-2.5 bg-blue-600 text-white rounded-xl font-medium hover:bg-blue-700 transition-colors">
            Select Project
          </button>
        </div>
      }

      <!-- Overall progress -->
      @if (selectedProject() && !loading() && !generating() && steps().length > 0) {
        <div class="rounded-xl border p-5"
          style="background:linear-gradient(135deg,#1F2937,#1D1384); border-color:#1D1384; box-shadow:0 4px 20px rgba(11,15,42,0.2);">
          <div class="flex flex-col gap-4 mb-4 lg:flex-row lg:items-center lg:justify-between">
            <div>
              <h3 class="text-base font-bold" style="color:#fff;">{{ selectedProject()?.title || 'Project' }} — Roadmap</h3>
              <p class="text-xs mt-0.5" style="color:#93C5FD;">Generated by AI mentor · Updated {{ Date.now() | date:'MMM d, y' }}</p>
            </div>
            <div class="flex items-center gap-1.5 text-xs font-semibold rounded-lg"
              style="background:rgba(255,255,255,0.1); color:#fff; padding:6px 12px;">
              <ng-icon name="lucideZap" [size]="'13'" style="color:#FBBF24;" />
              AI-Generated
            </div>
          </div>
          <div class="flex items-center justify-between mb-2">
            <span class="text-xs" style="color:#93C5FD;">Overall Progress</span>
            <span class="text-sm font-bold" style="color:#fff;">{{ overallProgress }}%</span>
          </div>
          <div style="height:8px; background:rgba(255,255,255,0.1); border-radius:99px; overflow:hidden;">
            <div style="height:100%; border-radius:99px; background:linear-gradient(90deg,#60A5FA,#60A5FA); transition:width 0.8s cubic-bezier(.4,0,.2,1);"
              [style.width.%]="overallProgress">
            </div>
          </div>
          <div class="mt-3 flex flex-wrap items-center gap-4 sm:gap-6">
            <div class="flex items-center gap-1.5">
              <div style="width:8px;height:8px;border-radius:50%;background:#34D399;"></div>
              <span class="text-xs" style="color:#93C5FD;">{{ completedSteps }} Completed</span>
            </div>
            <div class="flex items-center gap-1.5">
              <div style="width:8px;height:8px;border-radius:50%;background:#60A5FA;"></div>
              <span class="text-xs" style="color:#93C5FD;">1 In Progress</span>
            </div>
            <div class="flex items-center gap-1.5">
              <div style="width:8px;height:8px;border-radius:50%;background:rgba(255,255,255,0.2);"></div>
              <span class="text-xs" style="color:#93C5FD;">{{ pendingSteps }} Pending</span>
            </div>
          </div>
        </div>

        <!-- Roadmap timeline -->
        <div class="grid gap-4" style="grid-template-columns:1fr;">
          @for (step of steps(); track step.title; let i = $index) {
            <div class="flex gap-4">
              <!-- Timeline indicator -->
            <div class="flex flex-col items-center flex-shrink-0" style="width:40px;">
              <div class="flex items-center justify-center rounded-full"
                style="width:36px; height:36px; border:2px solid;"
                [style.background]="step.status === 'completed' ? '#059669' : step.status === 'in-progress' ? '#1D1384' : 'var(--surface-subtle)'"
                [style.border-color]="step.status === 'completed' ? '#059669' : step.status === 'in-progress' ? '#1D1384' : 'var(--border)'">
                @if (step.status === 'completed') {
                  <ng-icon name="lucideCheck" [size]="'16'" style="color:#fff;" />
                } @else if (step.status === 'in-progress') {
                  <ng-icon name="lucideZap" [size]="'14'" style="color:#fff;" />
                } @else {
                  <ng-icon name="lucideCircle" [size]="'14'" style="color:#D1D5DB;" />
                }
              </div>
              @if (i < steps().length - 1) {
                <div style="width:2px; flex:1; min-height:20px; margin-top:4px;"
                  [style.background]="step.status === 'completed' ? '#059669' : '#E5E7EB'">
                </div>
              }
            </div>

            <!-- Step card -->
            <div class="flex-1 rounded-xl border mb-4 overflow-hidden transition-all hover:shadow-sm"
              style="box-shadow:0 1px 4px rgba(11,15,42,0.04);"
              [style.background]="step.status === 'in-progress' ? 'var(--surface-accent)' : 'var(--surface)'"
              [style.border-color]="step.status === 'in-progress' ? 'var(--badge-blue-bg)' : 'var(--border)'">
              <div class="flex flex-col gap-4 px-5 py-4 lg:flex-row lg:items-start lg:justify-between">
                <div class="flex-1 min-w-0">
                  <div class="flex flex-wrap items-center gap-2 mb-1">
                    <span class="text-xs font-semibold px-1.5 py-0.5 rounded"
                      style="background:var(--badge-purple-bg); color:var(--badge-purple-text);">{{ step.phase }}</span>
                    <span class="text-xs font-medium px-1.5 py-0.5 rounded-full"
                      [style.background]="step.status === 'completed' ? 'var(--badge-green-bg)' : step.status === 'in-progress' ? 'var(--badge-blue-bg)' : 'var(--badge-neutral-bg)'"
                      [style.color]="step.status === 'completed' ? 'var(--badge-green-text)' : step.status === 'in-progress' ? 'var(--badge-blue-text)' : 'var(--badge-neutral-text)'">
                      {{ step.status === 'in-progress' ? 'In Progress' : step.status === 'completed' ? 'Completed' : 'Pending' }}
                    </span>
                  </div>
                  <h4 class="text-sm font-bold mb-1" style="color:var(--text-primary);">{{ step.title }}</h4>
                  <p class="text-xs leading-relaxed" style="color:var(--text-secondary);">{{ step.description }}</p>
                </div>
                <div class="flex flex-wrap items-center gap-2 flex-shrink-0">
                  <div class="flex items-center gap-1 text-xs" style="color:var(--text-muted);">
                    <ng-icon name="lucideCalendar" [size]="'11'" />
                    {{ step.dueDate }}
                  </div>
                  <button (click)="selectedStep.set(step); showEditStep.set(true)" class="flex items-center justify-center rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
                    style="width:26px; height:26px; background:transparent; border:none; cursor:pointer; color:var(--text-muted);"
                    [attr.aria-label]="'Edit ' + step.title">
                    <ng-icon name="lucideEdit" [size]="'13'" />
                  </button>
                </div>
              </div>

              <!-- Tasks checklist -->
              <div style="border-top:1px solid var(--border-subtle); padding:12px 20px;">
                <div class="flex flex-wrap gap-x-6 gap-y-1.5">
                  @for (task of step.tasks; track task.label) {
                    <div class="flex items-center gap-1.5">
                      <div class="flex items-center justify-center rounded flex-shrink-0"
                        style="width:14px; height:14px;"
                        [style.background]="task.done ? '#059669' : 'var(--badge-neutral-bg)'"
                        [style.border]="task.done ? 'none' : '1.5px solid var(--border)'">
                        @if (task.done) {
                          <ng-icon name="lucideCheck" [size]="'9'" style="color:#fff;" />
                        }
                      </div>
                      <span class="text-xs"
                        [style.color]="task.done ? 'var(--text-muted)' : 'var(--text-body)'"
                        [style.text-decoration]="task.done ? 'line-through' : 'none'">
                        {{ task.label }}
                      </span>
                    </div>
                  }
                </div>
              </div>
            </div>
          </div>
        }
        </div>
      }

      <!-- Project Selector Modal -->
      @if (showProjectSelector()) {
        <div class="fixed inset-0 z-50 flex items-center justify-center" role="dialog" aria-modal="true" aria-label="Select Project">
          <div class="modal-backdrop" (click)="showProjectSelector.set(false)"></div>
          <div class="relative rounded-2xl overflow-hidden" style="background:var(--surface); width:min(520px, calc(100vw - 24px)); box-shadow:0 24px 64px rgba(0,0,0,0.28); max-height:85vh; display:flex; flex-direction:column;">
            <div class="flex items-center justify-between px-6 py-5" style="border-bottom:1px solid var(--border-subtle);">
              <h2 class="text-base font-bold" style="color:var(--text-primary);">Select Project</h2>
              <button (click)="showProjectSelector.set(false)" class="flex items-center justify-center rounded-lg transition-colors hover:bg-gray-100 dark:hover:bg-gray-800" style="width:32px; height:32px; background:transparent; border:none; cursor:pointer; color:var(--text-muted);" aria-label="Close">
                <ng-icon name="lucideX" [size]="'16'" />
              </button>
            </div>
            <div style="padding:24px; overflow-y:auto; flex:1;">
              @if (projects().length === 0) {
                <p class="text-sm text-gray-500 text-center py-8">No projects found. Create a project first.</p>
              } @else {
                <div class="space-y-2">
                  @for (project of projects(); track project.id) {
                    <button (click)="selectProject(project)" class="w-full text-left p-4 rounded-lg border hover:border-blue-500 hover:bg-blue-50 dark:hover:bg-blue-900/20 transition-colors"
                      [style.border-color]="selectedProject()?.id === project.id ? '#1D1384' : 'var(--border)'"
                      [style.background]="selectedProject()?.id === project.id ? 'var(--surface-accent)' : 'transparent'">
                      <h3 class="font-semibold text-sm mb-1" style="color:var(--text-primary);">{{ project.title }}</h3>
                      <p class="text-xs text-gray-500 line-clamp-2">{{ project.description || 'No description' }}</p>
                      @if (project.sector) {
                        <span class="inline-block mt-2 text-xs px-2 py-0.5 rounded-full" style="background:var(--badge-blue-bg); color:var(--badge-blue-text);">{{ project.sector }}</span>
                      }
                    </button>
                  }
                </div>
              }
            </div>
          </div>
        </div>
      }

      <!-- Add Step Modal -->
      @if (showAddStep()) {
        <div class="fixed inset-0 z-50 flex items-center justify-center" role="dialog" aria-modal="true" aria-label="Add Step">
          <div class="modal-backdrop" (click)="showAddStep.set(false)"></div>
          <div class="relative rounded-2xl overflow-hidden" style="background:var(--surface); width:min(520px, calc(100vw - 24px)); box-shadow:0 24px 64px rgba(0,0,0,0.28); max-height:85vh; display:flex; flex-direction:column;">
            <div class="flex items-center justify-between px-6 py-5" style="border-bottom:1px solid var(--border-subtle);">
              <h2 class="text-base font-bold" style="color:var(--text-primary);">Add New Step</h2>
              <button (click)="showAddStep.set(false)" class="flex items-center justify-center rounded-lg transition-colors hover:bg-gray-100 dark:hover:bg-gray-800" style="width:32px; height:32px; background:transparent; border:none; cursor:pointer; color:var(--text-muted);" aria-label="Close">
                <ng-icon name="lucideX" [size]="'16'" />
              </button>
            </div>
            <div style="padding:24px; overflow-y:auto; flex:1;">
              <div class="space-y-4">
                <div class="grid grid-cols-2 gap-4">
                  <div>
                    <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Phase</label>
                    <input type="text" class="w-full text-sm rounded-lg border focus:outline-none" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans);" placeholder="e.g. Phase 6" />
                  </div>
                  <div>
                    <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Due Date</label>
                    <input type="date" class="w-full text-sm rounded-lg border focus:outline-none" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans);" />
                  </div>
                </div>
                <div>
                  <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Title</label>
                  <input type="text" class="w-full text-sm rounded-lg border focus:outline-none" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans);" placeholder="Step title" />
                </div>
                <div>
                  <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Description</label>
                  <textarea rows="3" class="w-full text-sm rounded-lg border focus:outline-none" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans); resize:vertical;" placeholder="Describe this phase..."></textarea>
                </div>
                <div>
                  <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Tasks (one per line)</label>
                  <textarea rows="4" class="w-full text-sm rounded-lg border focus:outline-none" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans); resize:vertical;" placeholder="Task 1&#10;Task 2&#10;Task 3"></textarea>
                </div>
              </div>
            </div>
            <div class="flex items-center justify-end gap-3 px-6 py-4" style="border-top:1px solid var(--border-subtle);">
              <button (click)="showAddStep.set(false)" class="text-sm font-semibold rounded-xl cursor-pointer" style="background:transparent; border:1.5px solid var(--border); color:var(--text-body); padding:8px 20px;">Cancel</button>
              <button (click)="showAddStep.set(false)" class="text-sm font-semibold rounded-xl cursor-pointer" style="background:linear-gradient(135deg,#1C4FC3,#1D1384); color:#fff; border:none; padding:8px 20px;">Add Step</button>
            </div>
          </div>
        </div>
      }

      <!-- Edit Step Modal -->
      @if (showEditStep()) {
        <div class="fixed inset-0 z-50 flex items-center justify-center" role="dialog" aria-modal="true" [attr.aria-label]="'Edit: ' + (selectedStep()?.title ?? '')">
          <div class="modal-backdrop" (click)="showEditStep.set(false)"></div>
          <div class="relative rounded-2xl overflow-hidden" style="background:var(--surface); width:min(520px, calc(100vw - 24px)); box-shadow:0 24px 64px rgba(0,0,0,0.28); max-height:85vh; display:flex; flex-direction:column;">
            <div class="flex items-center justify-between px-6 py-5" style="border-bottom:1px solid var(--border-subtle);">
              <h2 class="text-base font-bold" style="color:var(--text-primary);">Edit Step</h2>
              <button (click)="showEditStep.set(false)" class="flex items-center justify-center rounded-lg transition-colors hover:bg-gray-100 dark:hover:bg-gray-800" style="width:32px; height:32px; background:transparent; border:none; cursor:pointer; color:var(--text-muted);" aria-label="Close">
                <ng-icon name="lucideX" [size]="'16'" />
              </button>
            </div>
            <div style="padding:24px; overflow-y:auto; flex:1;">
              <div class="space-y-4">
                <div class="grid grid-cols-2 gap-4">
                  <div>
                    <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Phase</label>
                    <input type="text" class="w-full text-sm rounded-lg border focus:outline-none" [value]="selectedStep()?.phase ?? ''" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans);" />
                  </div>
                  <div>
                    <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Due Date</label>
                    <input type="text" class="w-full text-sm rounded-lg border focus:outline-none" [value]="selectedStep()?.dueDate ?? ''" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans);" />
                  </div>
                </div>
                <div>
                  <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Title</label>
                  <input type="text" class="w-full text-sm rounded-lg border focus:outline-none" [value]="selectedStep()?.title ?? ''" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans);" />
                </div>
                <div>
                  <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Description</label>
                  <textarea rows="3" class="w-full text-sm rounded-lg border focus:outline-none" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans); resize:vertical;">{{ selectedStep()?.description }}</textarea>
                </div>
                <div>
                  <label class="block text-xs font-semibold mb-1.5" style="color:var(--text-secondary);">Status</label>
                  <select class="w-full text-sm rounded-lg border focus:outline-none" style="padding:8px 12px; background:var(--surface-input); border-color:var(--border); color:var(--text-primary); font-family:var(--font-sans);">
                    <option [selected]="selectedStep()?.status === 'completed'">Completed</option>
                    <option [selected]="selectedStep()?.status === 'in-progress'">In Progress</option>
                    <option [selected]="selectedStep()?.status === 'pending'">Pending</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="flex items-center justify-end gap-3 px-6 py-4" style="border-top:1px solid var(--border-subtle);">
              <button (click)="showEditStep.set(false)" class="text-sm font-semibold rounded-xl cursor-pointer" style="background:transparent; border:1.5px solid var(--border); color:var(--text-body); padding:8px 20px;">Cancel</button>
              <button (click)="showEditStep.set(false)" class="text-sm font-semibold rounded-xl cursor-pointer" style="background:linear-gradient(135deg,#1C4FC3,#1D1384); color:#fff; border:none; padding:8px 20px;">Save Changes</button>
            </div>
          </div>
        </div>
      }
    </div>
  `,
})
export class RoadmapsComponent implements OnInit {
  private projectService = inject(ProjectService);
  protected readonly Date = Date; // Expose Date to template
  
  protected readonly showAddStep = signal(false);
  protected readonly showEditStep = signal(false);
  protected readonly selectedStep = signal<RoadmapStep | null>(null);
  protected readonly showProjectSelector = signal(false);
  protected readonly projects = signal<Project[]>([]);
  protected readonly selectedProject = signal<Project | null>(null);
  protected readonly loading = signal(false);
  protected readonly generating = signal(false);
  protected readonly error = signal('');
  
  protected readonly steps = signal<RoadmapStep[]>([
    {
      phase: 'Phase 1', title: 'Validate Product-Market Fit', dueDate: 'Feb 28, 2026', status: 'completed',
      description: 'Conduct customer discovery interviews, build MVP, and gather initial traction metrics to validate the core value proposition.',
      tasks: [
        { label: '50 customer interviews', done: true },
        { label: 'MVP launched',           done: true },
        { label: '100 beta users',         done: true },
        { label: 'NPS score > 40',         done: true },
      ],
    },
    {
      phase: 'Phase 2', title: 'Build Core Team & Legal Structure', dueDate: 'Mar 31, 2026', status: 'completed',
      description: 'Formalize the company, recruit key technical and business co-founders, and establish governance foundations.',
      tasks: [
        { label: 'Company registered (SARL)', done: true },
        { label: 'CTO recruited',             done: true },
        { label: 'Shareholder agreement',     done: true },
        { label: 'Startup label obtained',    done: false },
      ],
    },
    {
      phase: 'Phase 3', title: 'Fundraising — Pre-Seed Round', dueDate: 'Apr 30, 2026', status: 'in-progress',
      description: 'Prepare investor materials, pitch to angel network, and close a pre-seed round to fund 12 months of growth.',
      tasks: [
        { label: 'Pitch deck finalized',         done: true  },
        { label: 'Financial model built',        done: true  },
        { label: '20 investor meetings',         done: false },
        { label: 'Term sheet signed',            done: false },
        { label: 'Due diligence completed',      done: false },
      ],
    },
    {
      phase: 'Phase 4', title: 'Scale Product & User Acquisition', dueDate: 'Jun 30, 2026', status: 'pending',
      description: 'Use raised capital to scale the product, launch marketing campaigns, and hit 1,000 paying customers.',
      tasks: [
        { label: 'Hire 2 engineers',       done: false },
        { label: 'Launch growth campaigns', done: false },
        { label: '500 paying users',       done: false },
        { label: 'MRR of $15K',           done: false },
      ],
    },
    {
      phase: 'Phase 5', title: 'Seed Round & Market Expansion', dueDate: 'Oct 31, 2026', status: 'pending',
      description: 'Close seed round, expand to 2 additional markets, and build partnerships with key enterprise customers.',
      tasks: [
        { label: 'Seed round closed ($300K+)', done: false },
        { label: 'Expand to 2nd market',       done: false },
        { label: '3 enterprise pilots',        done: false },
      ],
    },
  ]);

  ngOnInit(): void {
    this.loadProjects();
  }

  loadProjects(): void {
    this.loading.set(true);
    this.projectService.listProjects().subscribe({
      next: (projects) => {
        this.projects.set(projects);
        this.loading.set(false);
        // Auto-select first project if available
        if (projects.length > 0 && !this.selectedProject()) {
          this.selectProject(projects[0]);
        }
      },
      error: (err) => {
        console.error('Failed to load projects:', err);
        this.error.set('Failed to load projects');
        this.loading.set(false);
      }
    });
  }

  selectProject(project: Project): void {
    this.selectedProject.set(project);
    this.showProjectSelector.set(false);
    this.loadRoadmap(project.id);
  }

  loadRoadmap(projectId: number): void {
    this.generating.set(true);
    this.error.set('');
    
    this.projectService.generateRoadmap(projectId).subscribe({
      next: (response) => {
        this.generating.set(false);
        if (response?.steps && Array.isArray(response.steps)) {
          const mappedSteps = this.mapBackendStepsToUI(response.steps);
          this.steps.set(mappedSteps);
        }
      },
      error: (err) => {
        console.error('Failed to generate roadmap:', err);
        this.error.set('Failed to generate roadmap. Please try again.');
        this.generating.set(false);
      }
    });
  }

  private mapBackendStepsToUI(backendSteps: any[]): RoadmapStep[] {
    return backendSteps.map((step, index) => ({
      phase: step.phase || `Phase ${index + 1}`,
      title: step.title || 'Untitled Step',
      description: step.description || '',
      dueDate: this.calculateDueDate(step.durationWeeks || 4, index),
      status: index === 0 ? 'in-progress' : 'pending',
      tasks: this.extractTasks(step.description)
    }));
  }

  private calculateDueDate(durationWeeks: number, stepIndex: number): string {
    const date = new Date();
    date.setDate(date.getDate() + (durationWeeks * 7 * (stepIndex + 1)));
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  }

  private extractTasks(description: string): { label: string; done: boolean }[] {
    // Extract bullet points or numbered items from description
    const lines = description.split('\n').filter(line => 
      line.trim().startsWith('-') || 
      line.trim().startsWith('•') || 
      /^\d+\./.test(line.trim())
    );
    
    if (lines.length === 0) {
      // Create generic tasks if no bullets found
      return [
        { label: 'Define objectives', done: false },
        { label: 'Execute plan', done: false },
        { label: 'Review results', done: false }
      ];
    }
    
    return lines.map(line => ({
      label: line.replace(/^[-•\d.]\s*/, '').trim(),
      done: false
    }));
  }

  regenerateRoadmap(): void {
    const project = this.selectedProject();
    if (project) {
      this.loadRoadmap(project.id);
    }
  }

  protected get overallProgress(): number {
    const allSteps = this.steps();
    const totalTasks = allSteps.reduce((sum, s) => sum + s.tasks.length, 0);
    const doneTasks = allSteps.reduce((sum, s) => sum + s.tasks.filter(t => t.done).length, 0);
    return totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;
  }

  protected get completedSteps(): number {
    return this.steps().filter(s => s.status === 'completed').length;
  }

  protected get pendingSteps(): number {
    return this.steps().filter(s => s.status === 'pending').length;
  }
}
