spring.application.name=partenariat-pi
server.port=8085
spring.config.import=optional:file:.env[.properties]

# MySQL its own DB
spring.datasource.url=jdbc:mysql://localhost:3306/partenariat_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.debug=true

# Zoom (Server-to-Server OAuth)
zoom.client-id=${ZOOM_CLIENT_ID:${Client_ID:}}
zoom.client-secret=${ZOOM_CLIENT_SECRET:${Client_Secret:}}
zoom.account-id=${ZOOM_ACCOUNT_ID:${Account_ID:}}
zoom.user-id=${ZOOM_USER_ID:me}
zoom.base-url=https://api.zoom.us